# Generated by Django 5.1.1 on 2024-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_products1_rename_course_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='video',
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
