# Generated by Django 5.1.1 on 2024-09-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_products_video_alter_products_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='none', max_length=200),
        ),
    ]
