# Generated by Django 5.1.1 on 2024-09-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Products',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products2',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
