# Generated by Django 5.1.1 on 2024-09-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_featured_products_products2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featured_products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='featured_products',
            name='name',
        ),
        migrations.RemoveField(
            model_name='featured_products',
            name='price',
        ),
        migrations.AlterField(
            model_name='featured_products',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
