# Generated by Django 5.1.1 on 2024-09-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_featured_products_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_products',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
