# Generated by Django 5.1.1 on 2024-09-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_featuredproducts_delete_featured_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedProducts',
            new_name='Productss',
        ),
    ]
