# Generated by Django 5.1.1 on 2024-09-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_featuredproducts_productss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productss',
            new_name='FeaturedProducts',
        ),
    ]
