# Generated by Django 5.1.1 on 2024-09-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_advertisingbanner_delete_featuredproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisingbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
