# Generated by Django 5.1.1 on 2024-09-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_advertisingbanner_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products1',
            old_name='video',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='products2',
            old_name='video',
            new_name='count',
        ),
        migrations.AddField(
            model_name='products1',
            name='description',
            field=models.TextField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='products1',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='products2',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
