# Generated by Django 5.1.1 on 2024-09-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_video_products1_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products2',
            name='description',
            field=models.TextField(default='none', max_length=200),
        ),
    ]
