# Generated by Django 4.2 on 2024-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
